name = "estudio-aline-andrade"
compatibility_date = "2025-12-23"
pages_build_output_dir = "./dist"

[vars]
STUDIO_PHONE = "5547991518816"

# [[d1_databases]]
# binding = "DB"
# database_name = "estudio-aline-andrade"
# database_id = "a5a224e4-f09e-4629-833c-12bafac2d045"
# preview_database_id = "DB"
